project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: Coding Intros
  author: Prof. Dr. Dominik Liebl
  date: last-modified
  date-format: "[Last Updated on] MMMM DD, YYYY"
  sidebar:
    logo: images/KU_Logo_2.png
    number-depth: 2
  search: true
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "Introduction to R"
      chapters:
        - R-01-Getting-Started.qmd
        - R-02-Datasets.qmd
        - R-03-Programming.qmd
        - R-04-Functions.qmd
        - R-05-Plotting.qmd
        - R-06-Monte-Carlo-Simulations.qmd
        - R-07-Regression.qmd
        - R-08-Notes-on-useful-packages.qmd
    - part: "Introduction to Python"
      chapters:
        - Python-01-Getting-Started.qmd
        - Python-02-Datasets.qmd
        - Python-03-Programming.qmd
        - Python-04-Functions.qmd
        - Python-05-Plotting.qmd
        - Python-06-Monte-Carlo-Simulations.qmd
        - Python-07-Regression.qmd
        - Python-08-Notes-on-useful-packages.qmd

bibliography: book.bib

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [flatly, darkly, theme.scss]
    html-math-method:
      method: mathjax
      url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML"
    number-sections: true
    code-link: true
    reference-links: true
    reference-location: margin
    knitr:
      opts_chunk:
        fig.align: center
        fig-align: center
  pdf:
    documentclass: scrreprt
    papersize: a4
    toc: true
    number-sections: true
    colorlinks: true
    keep-tex: false
    include-in-header: pdf-header.tex
    filters:
      - strip-ansi.lua
