---
title: "Introduction to R"
author: "Institute of Finance and Statistics"
date: 
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "R script for Econometrics I"
output:
  bookdown::gitbook: default
---
 

# Preface {-}


The purpose of this tutorial is to introduce the software package R that is used during the lectures, in problem sets, and in the tutorials. The pdf version of these lecture notes is on the [class website](https://ecampus.uni-bonn.de/). The html version is better formatted and can be found [here](https://bookdown.org/joachimfreyberger/r_tutorial_phd_econometrics/_book/). 

Some additional references and tutorials you might find helpful are:

-   The online textbook [Introduction to Econometrics with R](https://www.econometrics-with-r.org/) 
-   [Reference card for R commands](https://cran.r-project.org/doc/contrib/refcard.pdf)  
-   [Matlab/R reference ](https://cran.r-project.org/doc/contrib/Hiebeler-matlabR.pdf)   
-   [The official introduction to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)   
-   [www.r-project.org](https://www.r-project.org/other-docs.html)  
-   An R-package for learning R: [www.swirl.com](https://swirlstats.com/)   
-   A book project which covers also advanced issues such as "writing performant code" and "package development": [adv-r.had.co.nz](http://adv-r.had.co.nz/)    
-   Another excellent book: [R for Data Science](https://r4ds.had.co.nz/)    
-   [An introduction to statistical learning with R](https://www.statlearning.com/)   

Here are also links to more advanced tutorials:

-  [Introduction to data science](https://idc9.github.io/stor390/) 
-  [Creating dynamic graphics](https://gganimate.com/)  
-  [ChatGPT](https://openai.com/chatgpt/)

Why do we use R?

-    R is free of charge and can be downloaded from [https://cran.rstudio.com/](https://cran.rstudio.com/) 
-    The IDE RStudio for R is also free of charge and can be downloaded from  
     [https://rstudio.com/products/rstudio/download/#download](https://rstudio.com/products/rstudio/download/#download) 
-    R is equipped with one of the most flexible and powerful graphic routines available anywhere. For instance, check out one of the following repositories:
      - [Clean Graphs](http://shinyapps.org/apps/RGraphCompendium/index.php) 
      - [Publication ready plots](https://rpkgs.datanovia.com/ggpubr/index.html) 
-  Today, R is the de-facto standard for statistical science.




